version: '2.1'
services:
  rubis:
    build:
      context: ./Rubis
    depends_on:
     - rubisdb
    labels:
      loadbalancer: "apache"
  rubisdb:
    build:
      context: ./RubisDB
  rubisweb:
    build:
      context: ./RubisWeb
    ports:
     - "5002:80"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
     - rubis
    security_opt:
     - label:disable
  rubisclient:
    depends_on:
     - rubisdb
     - rubis
     - rubisweb
    build:
      context: ./RubisClient
    ports:
     - "5003:80"
    environment:
     - TARGET=emulator
